### ISSUE TITLE
Task's parent_stage is None

### ISSUE THREAD

**Issue by kristofarkas** [radical-collaboration/GB-SC18#28]
I am getting the following error when running entk:
```
2017-12-02 18:20:01,331: radical.entk.appmanager: MainProcess                     : synchronizer-thread: ERROR   : Unknown error in synchronizer: Entity: parent_stage, Expected (base) type(s) <type 'str'>, but got <type 'NoneType'>.. 
 Terminating thread
Traceback (most recent call last):
  File "/Users/kristof.farkas-pall/anaconda2/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 821, in _synchronizer
    task_update(msg, 'sync-to-enq', props.correlation_id, mq_channel)
  File "/Users/kristof.farkas-pall/anaconda2/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 628, in task_update
    completed_task.from_dict(msg['object'])
  File "/Users/kristof.farkas-pall/anaconda2/lib/python2.7/site-packages/radical/entk/task/task.py", line 589, in from_dict
    raise TypeError(entity='parent_stage', expected_type=str, actual_type=type(d['parent_stage']))
TypeError: Entity: parent_stage, Expected (base) type(s) <type 'str'>, but got <type 'NoneType'>.
```

From the error, a `Task` object's parent_stage is None. Why is this? Where could this error originate from? I am pretty sure, it's on my end, but I don't know how to debug this. The task is added to the stage with the `.add_tasks(task)` method for every new task. Why is this happing?

**Comment by vivek-bala** [comment]
Hey Kristoff, can you point me to the script that you are running.

**Comment by kristofarkas** [comment]
Script is [here](https://github.com/kristofarkas/bioradical/blob/master/example/esmacs.py).
The pipeline is created [here](https://github.com/kristofarkas/bioradical/blob/32d5035cdeea09f15ea011fc76e356cddbb73c32/bioradical/workflow.py#L21-L34).

**Comment by kristofarkas** [comment]
*Update:* when running entk with a bare-bones pipeline it works. The task/unit is submitted. This leads me to believe that the problem lies with how the pipeline is set up. As @andre-merzky said before, entk doesn't submit any units to the RP layer. Why could that be?

**Comment by kristofarkas** [comment]
It very probable that I am doing the pipeline setup incorrectly.

Here are the logs. Do you need any other files?
```
(radical-gpu) kristof.farkas-pall@julian~/Developer/bioradical/example$ python esmacs.py
2017-12-04 10:29:12,234: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.14 |Anaconda, Inc.| (default, Oct 5 2017, 02:28:52) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
2017-12-04 10:29:12,235: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    :                      pid: 9288
2017-12-04 10:29:12,235: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2017-12-04 10:29:12,252: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    : Resource Manager initialized
2017-12-04 10:29:12,252: radical.entk.resource_manager: MainProcess                     : MainThread     : DEBUG   : Validating resource description
2017-12-04 10:29:12,252: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    : Resource description validated
2017-12-04 10:29:12,252: radical.entk.resource_manager: MainProcess                     : MainThread     : DEBUG   : Populating resource manager object
2017-12-04 10:29:12,253: radical.entk.resource_manager: MainProcess                     : MainThread     : DEBUG   : Resource manager population successful
2017-12-04 10:29:12,253: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.14 |Anaconda, Inc.| (default, Oct 5 2017, 02:28:52) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
2017-12-04 10:29:12,253: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    :                      pid: 9288
2017-12-04 10:29:12,253: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2017-12-04 10:29:12,256: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Application Manager initialized
2017-12-04 10:29:12,258: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Workflow assigned to Application Manager
2017-12-04 10:29:12,258: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Setting up RabbitMQ system
2017-12-04 10:29:12,258: radical.entk.appmanager: MainProcess                     : MainThread     : DEBUG   : Setting up mq connection and channel
2017-12-04 10:29:12,266: radical.entk.appmanager: MainProcess                     : MainThread     : DEBUG   : Connection and channel setup successful
2017-12-04 10:29:12,267: radical.entk.appmanager: MainProcess                     : MainThread     : DEBUG   : Setting up all exchanges and queues
2017-12-04 10:29:12,502: radical.entk.appmanager: MainProcess                     : MainThread     : DEBUG   : All exchanges and queues are setup
2017-12-04 10:29:12,502: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Starting resource request submission
new session: [rp.session.julian.chem.ucl.ac.uk.kristof.farkas-pall.017504.0008]\
database   : [mongodb://radical:fg*2GT3^eB@crick.chem.ucl.ac.uk:27017/admin]  ok
create pilot manager                                                          ok
submit 1 pilot(s)
        .2017-12-04 10:31:19,055: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    : Pilot pilot.0000 state: PMGR_LAUNCHING_PENDING
                                                                     ok
2017-12-04 10:31:19,060: radical.entk.resource_manager: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: PMGR_LAUNCHING
2017-12-04 10:32:07,388: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    : Resource request submission successful.. waiting for pilot to go Active
2017-12-04 10:32:34,508: radical.entk.resource_manager: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: PMGR_ACTIVE_PENDING
2017-12-04 10:42:52,962: radical.entk.resource_manager: MainProcess                     : pmgr.0000.idler._state_pull_cb: INFO    : Pilot pilot.0000 state: PMGR_ACTIVE
2017-12-04 10:42:53,068: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    : Pilot is now active
2017-12-04 10:42:53,069: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Starting synchronizer thread
2017-12-04 10:42:53,069: radical.entk.appmanager: MainProcess                     : synchronizer-thread: INFO    : synchronizer thread started
True
2017-12-04 10:42:53,072: radical.entk.wfprocessor: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.14 |Anaconda, Inc.| (default, Oct 5 2017, 02:28:52) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
2017-12-04 10:42:53,072: radical.entk.wfprocessor: MainProcess                     : MainThread     : INFO    :                      pid: 9288
2017-12-04 10:42:53,073: radical.entk.wfprocessor: MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2017-12-04 10:42:53,109: radical.entk.wfprocessor: MainProcess                     : MainThread     : INFO    : Created WFProcessor object: radical.entk.wfprocessor.0000
2017-12-04 10:42:53,109: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Starting WFProcessor process from AppManager
2017-12-04 10:42:53,111: radical.entk.wfprocessor: MainProcess                     : MainThread     : INFO    : Starting WFprocessor process
2017-12-04 10:42:53,119: radical.entk.task_manager: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.14 |Anaconda, Inc.| (default, Oct 5 2017, 02:28:52) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
2017-12-04 10:42:53,120: radical.entk.task_manager: MainProcess                     : MainThread     : INFO    :                      pid: 9288
2017-12-04 10:42:53,121: radical.entk.task_manager: MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2017-12-04 10:42:53,127: radical.entk.task_manager: MainProcess                     : MainThread     : INFO    : Created task manager object: radical.entk.task_manager.0000
2017-12-04 10:42:53,127: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Starting task manager process from AppManager
2017-12-04 10:42:53,127: radical.entk.wfprocessor: wfprocessor                     : MainThread     : INFO    : WFprocessor started
2017-12-04 10:42:53,128: radical.entk.wfprocessor: wfprocessor                     : MainThread     : INFO    : Starting dequeue-thread
2017-12-04 10:42:53,128: radical.entk.wfprocessor: wfprocessor                     : dequeue-thread : INFO    : Dequeue thread started
2017-12-04 10:42:53,129: radical.entk.task_manager: MainProcess                     : MainThread     : INFO    : Starting task manager process
2017-12-04 10:42:53,129: radical.entk.wfprocessor: wfprocessor                     : MainThread     : INFO    : Starting enqueue-thread
2017-12-04 10:42:53,133: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : INFO    : enqueue-thread started
2017-12-04 10:42:53,135: radical.entk.task_manager: MainProcess                     : MainThread     : INFO    : Starting hearbeat thread
Active pipes:  1
WFP complete:  True
2017-12-04 10:42:53,150: radical.entk.task_manager: task-manager                    : MainThread     : INFO    : Task Manager process started
2017-12-04 10:42:53,153: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : DEBUG   : Attempting to sync radical.entk.pipeline.0000 with state SCHEDULING with AppManager
2017-12-04 10:42:53,164: radical.entk.appmanager: MainProcess                     : synchronizer-thread: INFO    : Received radical.entk.pipeline.0000 with state SCHEDULING
2017-12-04 10:42:53,166: radical.entk.appmanager: MainProcess                     : synchronizer-thread: INFO    : Found pipeline radical.entk.pipeline.0000, state SCHEDULING, completed False
2017-12-04 10:42:53,170: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : DEBUG   : radical.entk.pipeline.0000 with state SCHEDULING synced with AppManager
2017-12-04 10:42:53,172: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : INFO    : Transition of radical.entk.pipeline.0000 to new state SCHEDULING successful
2017-12-04 10:42:53,172: radical.entk.task_manager: MainProcess                     : heartbeat      : INFO    : Sent heartbeat request
2017-12-04 10:42:53,173: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : DEBUG   : Attempting to sync radical.entk.stage.0000 with state SCHEDULING with AppManager
2017-12-04 10:42:53,181: radical.entk.appmanager: MainProcess                     : synchronizer-thread: INFO    : Received radical.entk.stage.0000 with state SCHEDULING
2017-12-04 10:42:53,181: radical.entk.appmanager: MainProcess                     : synchronizer-thread: INFO    : Found parent pipeline: radical.entk.pipeline.0000
2017-12-04 10:42:53,182: radical.entk.appmanager: MainProcess                     : synchronizer-thread: DEBUG   : Found stage radical.entk.stage.0000
2017-12-04 10:42:53,184: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : DEBUG   : radical.entk.stage.0000 with state SCHEDULING synced with AppManager
2017-12-04 10:42:53,185: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : INFO    : Transition of radical.entk.stage.0000 to new state SCHEDULING successful
2017-12-04 10:42:53,186: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : DEBUG   : Attempting to sync radical.entk.task.0001 with state SCHEDULING with AppManager
2017-12-04 10:42:53,191: radical.entk.appmanager: MainProcess                     : synchronizer-thread: ERROR   : Unknown error in synchronizer: Entity: parent_stage, Expected (base) type(s) <type 'str'>, but got <type 'NoneType'>.. 
 Terminating thread
Traceback (most recent call last):
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 840, in _synchronizer
    task_update(msg, 'sync-to-enq', props.correlation_id, mq_channel)
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 635, in task_update
    completed_task.from_dict(msg['object'])
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/radical/entk/task/task.py", line 732, in from_dict
    raise TypeError(entity='parent_stage', expected_type=str, actual_type=type(d['parent_stage']))
TypeError: Entity: parent_stage, Expected (base) type(s) <type 'str'>, but got <type 'NoneType'>.

Exception in thread synchronizer-thread:
Traceback (most recent call last):
  File "/Users/kristof.farkas-pall/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/kristof.farkas-pall/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 888, in _synchronizer
    raise Error(text=ex)
Error: Error: Entity: parent_stage, Expected (base) type(s) <type 'str'>, but got <type 'NoneType'>.

2017-12-04 10:42:53,212: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Restarting synchronizer thread
2017-12-04 10:42:53,213: radical.entk.appmanager: MainProcess                     : synchronizer-thread: INFO    : synchronizer thread started
2017-12-04 10:42:53,227: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Restarting synchronizer thread
2017-12-04 10:42:53,228: radical.entk.appmanager: MainProcess                     : synchronizer-thread: INFO    : synchronizer thread started
2017-12-04 10:42:53,243: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Restarting synchronizer thread
2017-12-04 10:42:53,243: radical.entk.appmanager: MainProcess                     : synchronizer-thread: INFO    : synchronizer thread started
create unit manager                                                           ok
add 1 pilot(s)                                                                ok
2017-12-04 10:42:53,844: radical.entk.task_manager: task-manager                    : MainThread     : INFO    : Received heartbeat request
2017-12-04 10:42:53,845: radical.entk.task_manager: task-manager                    : MainThread     : INFO    : Sent heartbeat response
2017-12-04 10:43:03,184: radical.entk.task_manager: MainProcess                     : heartbeat      : INFO    : Received heartbeat response
2017-12-04 10:43:03,188: radical.entk.task_manager: MainProcess                     : heartbeat      : INFO    : Sent heartbeat request
2017-12-04 10:43:03,188: radical.entk.task_manager: task-manager                    : MainThread     : INFO    : Received heartbeat request
```

**Comment by kristofarkas** [comment]
@vivek-bala is there a constraint on the order of when one can call `.add_stages` and `.add_tasks`? In this case, first the pipeline is created, then all the stages are created and added to the pipeline with `.add_stages`. Then all the tasks are created and added one by one to the corresponding stage with `.add_tasks`. Could it be that the pipeline doesn't update the count of how many tasks are in the stage?

**Comment by vivek-bala** [comment]
Ah yes! I think you caught it correctly. In your case, the Pipeline consists of empty stage(s) and hence you see the error. The tasks need to be added to the stages before the stage is added to the Pipeline. Let me know if that resolves the issue.

I think the error message can be improved to reflect empty stages. I'm creating a list of issues suggesting improved debug messages. If the above suggestion solves this issue, please leave this ticket open. I will tag it and close it soon.

**Comment by kristofarkas** [comment]
Okay, I made the change, now it looks like [this](https://github.com/kristofarkas/bioradical/blob/315d1c2a9227c13321b8fb345e46111573081a11/bioradical/workflow.py#L21-L32).
The good news it that is seems to work, i.e. it submits the tasks as intended.
The bad news is that there is a *new* error that I'm getting. I think this has to do with the gpu branch that is used.
```
2017-12-04 17:51:09,231: radical.entk.task_processor: task-manager                    : MainThread     : ERROR   : CU creation failed, error: attribute set is not extensible/private (key cpu_processes) (/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/saga/attributes.py +1068 (_attributes_i_set)  :  raise se.IncorrectState ("attribute set is not extensible/private (key %s)" %  key))
2017-12-04 17:51:09,232: radical.entk.task_manager: task-manager                    : MainThread     : ERROR   : Task radical.entk.task.0001 submission failed, error: attribute set is not extensible/private (key cpu_processes) (/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/saga/attributes.py +1068 (_attributes_i_set)  :  raise se.IncorrectState ("attribute set is not extensible/private (key %s)" %  key))
``` 
This appears to be in the saga layer.

**Comment by andre-merzky** [comment]
you likely need to switch to the `feature/gpu` branch in SAGA, too.  What version are you currently using?  
 The `radical-stack` command should tell you.

**Comment by kristofarkas** [comment]
```
  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /Users/kristof.farkas-pall/radical-gpu

  radical.pilot        : 0.46.2
  radical.utils        : 0.46.2
  saga                 : 0.47-v0.46-53-gb342c0c@feature-gpu
```

**Comment by kristofarkas** [comment]
*Update:* the `rc/0.46.3` stack works again 🙏.

**Comment by vivek-bala** [comment]
You might already be doing this. But just to keep it safe, I will suggest two different virtualenvs for the two stacks you are using as opposed to upgrading the same VE.

**Comment by jdakka** [comment]
It appears that jphillips (the lead developer of NAMD on BW) has re-added the MPI version of NAMD, which allows us to revert back to the more stable RC stack. 

Unfortunately BW doesn't document which versions are available for use/which have been taken down without reason... it's happened many times where I've had to switch between versions and as a result switch radical-stack(s). 

As a long term solution I'm planning to bite the bullet and try to install our own version of NAMD
