### ISSUE TITLE
WFP doesn't schedule tasks

### ISSUE THREAD

**Issue by kristofarkas** [radical-collaboration/GB-SC18#29]
It seems that for some reason no tasks are submitted for execution. On the remote there is no `unit.XXXX` folder created.

The logs excluding the startup:
```
2017-12-03 18:29:50,792: radical.entk.wfprocessor: wfprocessor                     : MainThread     : INFO    : WFprocessor started
2017-12-03 18:29:50,793: radical.entk.task_manager: MainProcess                     : MainThread     : INFO    : Created task manager object: radical.entk.task_manager.0000
2017-12-03 18:29:50,793: radical.entk.wfprocessor: wfprocessor                     : MainThread     : INFO    : Starting dequeue-thread
2017-12-03 18:29:50,794: radical.entk.wfprocessor: wfprocessor                     : dequeue-thread : INFO    : Dequeue thread started
2017-12-03 18:29:50,794: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Starting task manager process from AppManager
2017-12-03 18:29:50,796: radical.entk.task_manager: MainProcess                     : MainThread     : INFO    : Starting task manager process
2017-12-03 18:29:50,794: radical.entk.wfprocessor: wfprocessor                     : MainThread     : INFO    : Starting enqueue-thread
2017-12-03 18:29:50,800: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : INFO    : enqueue-thread started
2017-12-03 18:29:50,802: radical.entk.task_manager: MainProcess                     : MainThread     : INFO    : Starting hearbeat thread
Active pipes:  1
WFP complete:  True
2017-12-03 18:29:50,830: radical.entk.task_manager: task-manager                    : MainThread     : INFO    : Task Manager process started
2017-12-03 18:29:50,839: radical.entk.appmanager: MainProcess                     : synchronizer-thread: INFO    : Received radical.entk.pipeline.0000 with state SCHEDULING
2017-12-03 18:29:50,840: radical.entk.appmanager: MainProcess                     : synchronizer-thread: INFO    : Found pipeline radical.entk.pipeline.0000, state SCHEDULING, completed False
2017-12-03 18:29:50,844: radical.entk.task_manager: MainProcess                     : heartbeat      : INFO    : Sent heartbeat request
create unit manager                                                           ok
add 1 pilot(s)                                                                ok
2017-12-03 18:29:51,718: radical.entk.task_manager: task-manager                    : MainThread     : INFO    : Received heartbeat request
2017-12-03 18:29:51,718: radical.entk.task_manager: task-manager                    : MainThread     : INFO    : Sent heartbeat response
2017-12-03 18:30:00,854: radical.entk.task_manager: MainProcess                     : heartbeat      : INFO    : Received heartbeat response
2017-12-03 18:30:00,858: radical.entk.task_manager: MainProcess                     : heartbeat      : INFO    : Sent heartbeat request
2017-12-03 18:30:00,860: radical.entk.task_manager: task-manager                    : MainThread     : INFO    : Received heartbeat request
2017-12-03 18:30:00,860: radical.entk.task_manager: task-manager                    : MainThread     : INFO    : Sent heartbeat response
```
From then on it's just this send-receive cycle.

The *only* pipeline that I'm submitting looks like this:
```python
print p
    for s in p.stages:
        print '\t', s
        for t in s.tasks:
             print '\t\t',t

<radical.entk.pipeline.pipeline.Pipeline object at 0x10b83c9d0>
	<radical.entk.stage.stage.Stage object at 0x10b8434d0>
		<radical.entk.task.task.Task object at 0x10b843710>
	<radical.entk.stage.stage.Stage object at 0x10b843210>
		<radical.entk.task.task.Task object at 0x10b8436d0>
	<radical.entk.stage.stage.Stage object at 0x10b843490>
		<radical.entk.task.task.Task object at 0x10b843810>
	<radical.entk.stage.stage.Stage object at 0x10b843550>
		<radical.entk.task.task.Task object at 0x10b843910>
```

Any ideas what could be the problem?

**Comment by jdakka** [comment]
@kristofarkas can you tar and send the rp folder and the rp folder in radical.pilot.sandbox on the agent side? 

Btw are you running this on Blue Waters? And if so, are you using the radical GPU stack?

**Comment by kristofarkas** [comment]
On BW and rc/0.46.3 stack.

**Comment by kristofarkas** [comment]
[rp.local.tar.gz](https://github.com/radical-collaboration/GB-SC18/files/1525054/rp.local.tar.gz)
[rp.blue_waters.tar.gz](https://github.com/radical-collaboration/GB-SC18/files/1525055/rp.blue_waters.tar.gz)

**Comment by jdakka** [comment]
This is an error in the runtime

@andre-merzky I checked the logs in the client side `rp.local.tar` `rp.session.julian.chem.ucl.ac.uk.kristof.farkas-pall.017503.0002/pmgr.0000.log` 

```
0000.idler._state_pull_cb: ERROR   : abort: RuntimeError("can't route 'state_pubsub' notification: []",)
Traceback (most recent call last):
  File "/Users/kristof.farkas-pall/anaconda2/lib/python2.7/site-packages/radical/utils/threads.py", line 375, in _run
    if not self.work_cb():
  File "/Users/kristof.farkas-pall/anaconda2/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 952, in work_cb
    ret = self._cb()
  File "/Users/kristof.farkas-pall/anaconda2/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 256, in _state_pull_cb
    if not self._update_pilot(pilot_dict, publish=True):
  File "/Users/kristof.farkas-pall/anaconda2/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 332, in _update_pilot
    self.advance(pilot_dict, s, publish=publish, push=False)
  File "/Users/kristof.farkas-pall/anaconda2/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1363, in advance
    self.publish(rpc.STATE_PUBSUB, {'cmd': 'update', 'arg': to_publish})
  File "/Users/kristof.farkas-pall/anaconda2/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1431, in publish
    self._publishers.keys()))
RuntimeError: can't route 'state_pubsub' notification: []
2017-12-03 18:32:50,812: pmgr.0000           : MainProcess                     : pmgr.0000.idler._state_pull_cb: INFO    : put message: [pmgr.0000.idler._state_pull_cb.thread] RuntimeError("can't route 'state_pubsub' notification: []",)
2017-12-03 18:32:50,813: pmgr.0000           : MainProcess                     : pmgr.0000.idler._state_pull_cb: DEBUG   : ru_finalize_child (NOOP)
2017-12-03 18:32:50,813: pmgr.0000           : MainProcess                     : pmgr.0000.idler._state_pull_cb: DEBUG   : ru_finalize_common (NOOP)
2017-12-03 18:32:50,814: pmgr.0000           : MainProcess                     : pmgr.0000.idler._state_pull_cb: INFO    : put message: [pmgr.0000.idler._state_pull_cb.thread] terminating
2017-12-03 18:32:51,264: pmgr.0000           : MainProcess                     : pmgr.0000.subscriber._state_sub_cb: DEBUG   : ru_finalize_child (NOOP)
2017-12-03 18:32:51,523: pmgr.0000           : MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : put message: [pmgr.0000.subscriber._state_sub_cb.thread] terminating
```

**Comment by andre-merzky** [comment]
I don't think the RP layer gets any units:

```
 thinkie  merzky  …/downloads/t/rp.session.julian.chem.ucl.ac.uk.kristof.farkas-pall.017503.0002   $ grep unit.000000 *log
 thinkie  merzky  …/downloads/t/rp.session.julian.chem.ucl.ac.uk.kristof.farkas-pall.017503.0002  1   $ 
```

I also don't see any error messages in the logs, apart from those created during termination.  Could that be an EnTK issue?  The EnTK logs were not in the sandbox AFAICS.

@vivek-bala : would it make sense to always store the entk logs and profiles in the same session sandbox, to make it easier for users to pack things up?

**Comment by jdakka** [comment]
@kristofarkas can you also send *.entk.*0000.prof files as well? Those should also be on the client side where rp.local is located

**Comment by kristofarkas** [comment]
[rp.entk.tar.gz](https://github.com/radical-collaboration/GB-SC18/files/1525075/rp.entk.tar.gz)

**Comment by jdakka** [comment]
can you run it with `export RADICAL_VERBOSE="DEBUG"` I think you have it set currently to `INFO`

**Comment by kristofarkas** [comment]
```
2017-12-03 19:44:14,954: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.14 |Anaconda, Inc.| (default, Oct 5 2017, 02:28:52) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
2017-12-03 19:44:14,955: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    :                      pid: 85530
2017-12-03 19:44:14,955: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2017-12-03 19:44:15,466: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    : Resource Manager initialized
2017-12-03 19:44:15,466: radical.entk.resource_manager: MainProcess                     : MainThread     : DEBUG   : Validating resource description
2017-12-03 19:44:15,466: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    : Resource description validated
2017-12-03 19:44:15,466: radical.entk.resource_manager: MainProcess                     : MainThread     : DEBUG   : Populating resource manager object
2017-12-03 19:44:15,466: radical.entk.resource_manager: MainProcess                     : MainThread     : DEBUG   : Resource manager population successful
2017-12-03 19:44:15,467: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.14 |Anaconda, Inc.| (default, Oct 5 2017, 02:28:52) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
2017-12-03 19:44:15,467: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    :                      pid: 85530
2017-12-03 19:44:15,467: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2017-12-03 19:44:15,471: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Application Manager initialized
2017-12-03 19:44:15,473: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Workflow assigned to Application Manager
2017-12-03 19:44:15,473: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Setting up RabbitMQ system
2017-12-03 19:44:15,473: radical.entk.appmanager: MainProcess                     : MainThread     : DEBUG   : Setting up mq connection and channel
2017-12-03 19:44:15,482: radical.entk.appmanager: MainProcess                     : MainThread     : DEBUG   : Connection and channel setup successful
2017-12-03 19:44:15,483: radical.entk.appmanager: MainProcess                     : MainThread     : DEBUG   : Setting up all exchanges and queues
2017-12-03 19:44:15,641: radical.entk.wfprocessor: wfprocessor                     : dequeue-thread : ERROR   : Unable to receive message from completed queue: (404, "NOT_FOUND - no queue 'completedq-1' in vhost '/'")
2017-12-03 19:44:15,643: radical.entk.wfprocessor: wfprocessor                     : dequeue-thread : ERROR   : Error in dequeue-thread: (404, "NOT_FOUND - no queue 'completedq-1' in vhost '/'")
Traceback (most recent call last):
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 386, in _dequeue
    method_frame, header_frame, body = mq_channel.basic_get(queue=self._completed_queue[0])
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2034, in basic_get
    self._basic_getempty_result.is_ready)
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1250, in _flush_output
    *waiters)
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 455, in _flush_output
    self._impl.ioloop.poll()
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 245, in poll
    self._poller.poll()
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 816, in poll
    self._dispatch_fd_events(fd_event_map)
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 625, in _dispatch_fd_events
    handler(fileno, events)
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 395, in _handle_events
    self._handle_read()
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 449, in _handle_read
    self._on_data_available(data)
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/pika/connection.py", line 1938, in _on_data_available
    self._process_frame(frame_value)
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/pika/connection.py", line 2059, in _process_frame
    if self._process_callbacks(frame_value):
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/pika/connection.py", line 2040, in _process_callbacks
    frame_value)  # Args
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/pika/callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1316, in _on_channel_closed
    method.reply_text)
ChannelClosed: (404, "NOT_FOUND - no queue 'completedq-1' in vhost '/'")

Exception in thread dequeue-thread:
Traceback (most recent call last):
  File "/Users/kristof.farkas-pall/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/kristof.farkas-pall/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/kristof.farkas-pall/radical-gpu/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 565, in _dequeue
    raise Error(text=ex)
Error: Error: (404, "NOT_FOUND - no queue 'completedq-1' in vhost '/'")

2017-12-03 19:44:15,779: radical.entk.appmanager: MainProcess                     : MainThread     : DEBUG   : All exchanges and queues are setup
2017-12-03 19:44:15,779: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Starting resource request submission
new session: [rp.session.julian.chem.ucl.ac.uk.kristof.farkas-pall.017503.0005]\
database   : [mongodb://radical:fg*2GT3^eB@crick.chem.ucl.ac.uk:27017/admin]  ok
create pilot manager                                                          ok
submit 1 pilot(s)
        .2017-12-03 19:44:21,665: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    : Pilot pilot.0000 state: PMGR_LAUNCHING_PENDING
                                                                     ok
2017-12-03 19:44:21,669: radical.entk.resource_manager: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: PMGR_LAUNCHING
2017-12-03 19:44:44,510: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    : Resource request submission successful.. waiting for pilot to go Active
2017-12-03 19:44:59,253: radical.entk.resource_manager: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: PMGR_ACTIVE_PENDING

```

**Comment by jdakka** [comment]
@kristofarkas I think the rabbitmq host you're using is not setup properly. It's trying to connect to `vhost '/'` which probably doesn't exist.  

@vivek-bala or @andre-merzky  what do you think?

**Comment by kristofarkas** [comment]
I reran the script, and the error (relating to rabbitmq above) didn't show up. But that could be the problem nonetheless. What do you mean by correctly set up? I didn't do any "setting up", just installed the server as per instruction from their website.

**Comment by jdakka** [comment]
how are you running appman? how did you specify the port?
i.e.:
`appman = AppManager(port = 32775)`

or `appman = AppManager(hostname = 'two.radical-project.org', port = 32775)`

**Comment by kristofarkas** [comment]
I leave it blank, so it uses the default RabbitMQ port.

**Comment by jdakka** [comment]
I think you need to specify the port...the default looks like this (from the entk doc): http://radicalentk-06.readthedocs.io/en/arch-v0.6/api/appman.html?highlight=AppManager

**Comment by kristofarkas** [comment]
Yes, that's where the rabbit-mq is. And it worked for a long time.

**Comment by andre-merzky** [comment]
Assuming you deployed RabbitMQ via docker, could you please send the output of `docker ps`?

**Comment by kristofarkas** [comment]
No, I have it installed on a macOS computer via brew.

**Comment by andre-merzky** [comment]
Thanks.  Is there an easy way to verify if the service is still running and accessible?  You may have done so already I guess...  But as Jumana, I also would think that the error message indicates problem to contact the RabbitMQ service - either because the service has troubles, because the service endpoint URL is incorrectly communicated, or EnTK sends something invalid (like talking to a queue `completedq-1` which did not get created before).

Are there any EnTK logfiles available?  If so, can you please attach them?  Thanks!

**Comment by kristofarkas** [comment]
Above are all the files that I could find related to radical. Do you want anything else? The entk logs are [here](https://github.com/radical-collaboration/GB-SC18/files/1525075/rp.entk.tar.gz).

I reinstalled the whole RabbitMQ server, and the problem still exists. It was working properly for quite a while, and this problem just popped up at some point.

**Comment by kristofarkas** [comment]
*Update:* when running entk with a bare-bones pipeline it works. The task/unit is submitted. This leads me to believe that the problem lies with how the pipeline is set up. As you said before, entk doesn't submit any units to the RP layer. Why could that be?

**Comment by vivek-bala** [comment]
Hey Andre. Currently the logs are written to STDOUT and not to files. I agree it will be beneficial to write them to files. I am not sure if I want to put it under the session folder as EnTK needs to be independent of RP as much as  possible. 

I agree with the others that it does look like its coming from the RabbitMQ connectivity. If it still exists, can you give me the output of ```rabbitmqctl list_queues list_exchanges``` please? @kristofarkas since you mentioned this could be because of the way the pipelines are created, is this issue related to #28 ?

**Comment by andre-merzky** [comment]
I don't think that using the same folder makes it dependent.  Like, you can create a EnTK session ID, and put log files into a subdir with that ID as name - and then can also force that ID onto RP.  That is not a dependency, as you can do the same for a different backend *or not* w/o loosing anything.

**Comment by vivek-bala** [comment]
Yes, I see what you mean! Sounds good to me.

**Comment by kristofarkas** [comment]
@vivek-bala all these errors started at the same time, so I am assuming they are related (to #28).

**Comment by kristofarkas** [comment]
Closing this. The solution to #28 fixed this too.
